### ISSUE TITLE
Spinning Wheel - Never Loads

### ISSUE THREAD

**Issue by MrKuenning** [bit9labs/sd-masonry#2]
The tab never loads.
I do use a custom output folder in the settings. 

Arguments:
--listen --port 7799 --api  --xformers --medvram-sdxl --enable-insecure-extension-access --disable-safe-unpickle 
--styles-file E:\AI\MODELS\styles-full.csv 
--ckpt-dir E:\AI\MODELS\Stable-diffusion 
--lora-dir E:\AI\MODELS\LoRA 
--embeddings-dir E:\AI\MODELS\Embeddings

Output directory for T2I
E:\AI\Output\Txt2img

![2023-09-11 10_42_15-NVIDIA GeForce Overlay DT](https://github.com/bit9labs/sd-masonry/assets/16549268/6d6a10cd-fb5b-493d-9a5f-7536fe958d85)

I get no errors in the console.

```
----------------------------------------------------------------------------
venv "E:\AI\A1111\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Checking ReActor requirements... Ok
You are up to date with the most recent release.
Launching Web UI with arguments: --listen --port 7799 --api --update-check --xformers --medvram-sdxl --enable-insecure-extension-access --disable-safe-unpickle --gradio-auth xxx:xxx --styles-file E:\AI\MODELS\styles-full.csv --ckpt-dir E:\AI\MODELS\Stable-diffusion --lora-dir E:\AI\MODELS\LoRA --embeddings-dir E:\AI\MODELS\Embeddings
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: E:\AI\A1111\extensions\Civitai-Helper-axilesoft\setting.json
2023-09-11 10:40:25,496 - ControlNet - INFO - ControlNet v1.1.410
ControlNet preprocessor location: E:\AI\A1111\extensions\Controlnet\annotator\downloads
2023-09-11 10:40:25,635 - ControlNet - INFO - ControlNet v1.1.410
sd-webui-prompt-all-in-one background API service started successfully.
10:40:26 - ReActor - STATUS - Running v0.4.1
[-] ADetailer initialized. version: 23.9.2, num models: 12
Loading weights [f0d4872d24] from E:\AI\MODELS\Stable-diffusion\Z-Inpainting\Realistic Vision 5.1-inpainting.safetensors
3440 1440
1390
Creating model from config: E:\AI\A1111\configs\v1-inpainting-inference.yaml
Applying attention optimization: xformers... done.
Model loaded in 4.3s (load weights from disk: 0.9s, create model: 0.5s, apply weights to model: 0.8s, load textual inversion embeddings: 1.2s, calculate empty prompt: 0.8s).
Running on local URL:  http://0.0.0.0:7799

To create a public link, set `share=True` in `launch()`.
Startup time: 31.5s (prepare environment: 4.2s, import torch: 6.6s, import gradio: 0.8s, setup paths: 0.8s, initialize shared: 0.1s, other imports: 0.5s, setup codeformer: 0.1s, list SD models: 0.4s, load scripts: 5.4s, create ui: 5.2s, gradio launch: 6.9s, app_started_callback: 0.5s).
```

**Comment by bit9labs** [comment]
Thanks for the feedback it should pull from the custom directory, so I don't think that is the issue. 
- Is this only when you first start up your server and visit for a first time? 
- Does it work after you hit the refresh button?
- Are you running the latest version of webUI? (I had to make changes due to the new gradio version)

**Comment by MrKuenning** [comment]
> Thanks for the feedback it should pull from the custom directory, so I don't think that is the issue.
> 
> * Is this only when you first start up your server and visit for a first time?
This happened after reboot as well as any time I went to the tab.
> * Does it work after you hit the refresh button?
Refresh did nothing.
> * Are you running the latest version of webUI? (I had to make changes due to the new gradio version)
Yes I am running 1.6, (Build listed in screenshot above)

However, after updating today, the tab has disappeared completely.
I tried restarting the UI and I dont even see it listed in the UI tab settings.

**Comment by MrKuenning** [comment]
```
----------------------------------------------------------------------------
venv "E:\AI\A1111\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Checking ReActor requirements... Ok
Install sd-masonry...
Found version v1
You are up to date with the most recent release.
Launching Web UI with arguments: --listen --port 7799 --api --update-check --xformers --medvram-sdxl --enable-insecure-extension-access --disable-safe-unpickle --styles-file E:\AI\MODELS\styles-full.csv --ckpt-dir E:\AI\MODELS\Stable-diffusion --lora-dir E:\AI\MODELS\LoRA --embeddings-dir E:\AI\MODELS\Embeddings

Loading weights [0fd6e22bff] from E:\AI\MODELS\Stable-diffusion\Z-Inpainting\GeFeMi V2.1 Inpainting.safetensors
3440 1440
1390
Creating model from config: E:\AI\A1111\configs\v1-inpainting-inference.yaml
Applying attention optimization: xformers... done.

*** Error executing callback ui_tabs_callback for E:\AI\A1111\extensions\sd-masonry\scripts\main.py
    Traceback (most recent call last):
      File "E:\AI\A1111\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "E:\AI\A1111\extensions\sd-masonry\scripts\main.py", line 153, in on_ui_tabs
        html = refresh_images(1)
      File "E:\AI\A1111\extensions\sd-masonry\scripts\main.py", line 147, in refresh_images
        return get_page(page_index)
      File "E:\AI\A1111\extensions\sd-masonry\scripts\main.py", line 120, in get_page
        parameters = parse_generation_parameters(geninfo)
      File "E:\AI\A1111\modules\generation_parameters_copypaste.py", line 244, in parse_generation_parameters
        found_styles, prompt, negative_prompt = shared.prompt_styles.extract_styles_from_prompt(prompt, negative_prompt)
      File "E:\AI\A1111\modules\styles.py", line 123, in extract_styles_from_prompt
        is_match, new_prompt, new_neg_prompt = extract_style_from_prompts(style, prompt, negative_prompt)
      File "E:\AI\A1111\modules\styles.py", line 59, in extract_style_from_prompts
        match_positive, extracted_positive = extract_style_text_from_prompt(style.prompt, prompt)
      File "E:\AI\A1111\modules\styles.py", line 39, in extract_style_text_from_prompt
        left, right = stripped_style_text.split("{prompt}", 2)
    ValueError: too many values to unpack (expected 2)
---

Running on local URL:  http://0.0.0.0:7799
Model loaded in 11.9s (load weights from disk: 2.1s, create model: 0.5s, apply weights to model: 2.8s, apply half(): 1.0s, load VAE: 0.1s, load textual inversion embeddings: 4.5s, calculate empty prompt: 0.8s).
```

**Comment by bit9labs** [comment]
One of the updates II made was to include the prompt and meta as part of the lighbox. It looks like somehow it is unable to parse what ever meta is provided in one of your photos. As this is a core function provided by A111 I cannot change it, the best I can do is put a try: catch: around this process and ignore any files that are not parseable.

**Comment by bit9labs** [comment]
I pushed that change.

Are you able to provide an image that this fails on?

**Comment by MrKuenning** [comment]
So it parses all of the photo during the webUI boot?

Here is a photo in my output folder.
I will try to clear my output folder and restart the UI and see if that resolves it.
Then I will try to remove and re-add the extension.

![2023-09-09 015426 - 902788828 - 1600x896 - Sdxl Base 1 0 - woman on a farm, _lora_James R  Eads Style_0 9_,  James R  Eads Style page](https://github.com/bit9labs/sd-masonry/assets/16549268/9f067292-5651-4e9d-a75d-60e0085ef828)

**Comment by MrKuenning** [comment]
After clearing out my output folder the TAB showed back up.

I generated this image.
![2023-09-14 113310 - 194278833 - 512x512 - DREAMSHAPER 8 0 - A cute rubber ducky](https://github.com/bit9labs/sd-masonry/assets/16549268/a9ef7356-9a03-4d12-a167-040f842876da)

Went to the tab and hit refresh and the console spit out this:
```
  File "E:\AI\A1111\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AI\A1111\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\AI\A1111\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AI\A1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AI\A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\AI\A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\AI\A1111\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\AI\A1111\extensions\sd-masonry\scripts\main.py", line 147, in refresh_images
    return get_page(page_index)
  File "E:\AI\A1111\extensions\sd-masonry\scripts\main.py", line 120, in get_page
    parameters = parse_generation_parameters(geninfo)
  File "E:\AI\A1111\modules\generation_parameters_copypaste.py", line 244, in parse_generation_parameters
    found_styles, prompt, negative_prompt = shared.prompt_styles.extract_styles_from_prompt(prompt, negative_prompt)
  File "E:\AI\A1111\modules\styles.py", line 123, in extract_styles_from_prompt
    is_match, new_prompt, new_neg_prompt = extract_style_from_prompts(style, prompt, negative_prompt)
  File "E:\AI\A1111\modules\styles.py", line 59, in extract_style_from_prompts
    match_positive, extracted_positive = extract_style_text_from_prompt(style.prompt, prompt)
  File "E:\AI\A1111\modules\styles.py", line 39, in extract_style_text_from_prompt
    left, right = stripped_style_text.split("{prompt}", 2)
ValueError: too many values to unpack (expected 2)
```
The Tab says error.
![2023-09-14 11_34_06-NVIDIA GeForce Overlay DT](https://github.com/bit9labs/sd-masonry/assets/16549268/a8861ef1-10f4-4867-a5fa-e083631c2694)

**Comment by MrKuenning** [comment]
I updated to your build 6c8d8404 and restarted the web UI.
No errors in the console or un the UI, but I don't see any images.

**Comment by jwvanderbeck** [comment]
Having this same issue.  The spinning wheel will go for a bit, then after it is done and goes away I have no images.
I also use the Infinite Image Browser extension and it loads all my images just fine as best I can see.

No errors or other information appears to be shown in the terminal window.

**Comment by bit9labs** [comment]
@jwvanderbeck Do you put your output images in the default directory or somewhere else?

Does your txt2img directory have subfolders or are all your files flat in the output folder?

**Comment by jwvanderbeck** [comment]
They are to a custom location, and have subfolders using the option in A111 that outputs them to dated subfolders

**Comment by private-jobe** [comment]
Using standard output with dated sub-folders. This happens on first load. If stepping to other page it is okay and stops spinning. Pushing "first page" button enters first page flawlessly. Pressing "first page" button again makes the spinner go round and round. Same if using "last page" button twice.
