### ISSUE TITLE
sqlite3.OperationalError: no such table: images

### ISSUE THREAD

**Issue by d8ahazard** [bit9labs/sd-masonry#4]
Sometimes, when I just clone the extension repository into my AUTO folder and restart, I get an error that the extension can't find the Images table in the DB. Perhaps some kind of error checking for this would help?

[AUTO] *** Error executing callback ui_tabs_callback for /opt/rd/stable-diffusion-webui/extensions/sd-masonry/scripts/main.py
[AUTO] Traceback (most recent call last):
[AUTO] File "/opt/rd/stable-diffusion-webui/modules/script_callbacks.py", line 166, in ui_tabs_callback
[AUTO] res += c.callback() or []
[AUTO] File "/opt/rd/stable-diffusion-webui/extensions/sd-masonry/scripts/main.py", line 157, in on_ui_tabs
[AUTO] html = refresh_images(1)
[AUTO] File "/opt/rd/stable-diffusion-webui/extensions/sd-masonry/scripts/main.py", line 150, in refresh_images
[AUTO] traverse_all_files(dir_path)
[AUTO] File "/opt/rd/stable-diffusion-webui/extensions/sd-masonry/scripts/main.py", line 36, in traverse_all_files
[AUTO] c.execute("DELETE FROM images")
[AUTO] sqlite3.OperationalError: no such table: images
[AUTO]
[AUTO] ---

**Comment by bit9labs** [comment]
Can you elaborate on what an AUTO folder is? Do you mean the a1111/extensions folder?

Had you had it installed and then removed it? The SQLite table is created by install.py. This runs each time A1111 is restarted or the plugin is enabled from the extensions tab.

If previously installed, did you delete the sqlite.db file. This is specifically excluded from the repo.
